-- Ayslock database schema for Supabase. Generated by `npm run db:schema`; do not edit by hand.
-- Paste into Supabase → SQL Editor → New query → Run. Safe to run once on an empty project.
-- (You can also skip this: the app applies the same migrations itself on first start.)

begin;

create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());

-- ===== 20260930000001_schema.sql =====
-- Ayslock core schema. Portable Postgres (runs on Supabase, plain Postgres 14+ and PGlite).
-- All timestamps are timestamptz (stored as UTC). Each provider keeps an IANA timezone,
-- and every appointment snapshots the provider timezone it was booked in.

create extension if not exists btree_gist;

create table providers (
  id uuid primary key default gen_random_uuid(),
  -- Auth user id: auth.users.id on Supabase, demo_users.id in local demo mode.
  owner_id uuid not null unique,
  email text not null,
  username text not null,
  display_name text not null check (char_length(display_name) between 1 and 80),
  bio text not null default '' check (char_length(bio) <= 500),
  avatar_url text,
  timezone text not null,
  location_kind text not null default 'in_person' check (location_kind in ('in_person', 'online')),
  location_text text not null default '' check (char_length(location_text) <= 200),
  access_mode text not null default 'open' check (access_mode in ('open', 'approval', 'private')),
  min_notice_minutes integer not null default 120 check (min_notice_minutes between 0 and 20160),
  horizon_days integer not null default 60 check (horizon_days between 1 and 365),
  buffer_minutes integer not null default 0 check (buffer_minutes between 0 and 240),
  pending_expiry_hours integer not null default 24 check (pending_expiry_hours between 1 and 168),
  access_link_days integer not null default 30 check (access_link_days between 1 and 365),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- 3 to 30 chars, lowercase letters, digits and underscores, no leading/trailing underscore.
  constraint providers_username_format check (username ~ '^[a-z0-9][a-z0-9_]{1,28}[a-z0-9]$')
);
-- Case-insensitive uniqueness. The app always stores lowercase; the index is the
-- final guard against two concurrent sign-ups claiming the same name.
create unique index providers_username_lower_key on providers (lower(username));

create table services (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  description text not null default '' check (char_length(description) <= 300),
  duration_minutes integer not null check (duration_minutes between 5 and 720),
  price_cents integer check (price_cents is null or price_cents >= 0),
  currency text not null default 'USD',
  active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now()
);
create index services_provider_idx on services (provider_id);

-- Weekly working hours in the provider's local time. Several rows per weekday are
-- allowed; the gaps between them are breaks. weekday is ISO (1 = Monday, 7 = Sunday).
create table weekly_hours (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  weekday smallint not null check (weekday between 1 and 7),
  start_minute integer not null check (start_minute between 0 and 1439),
  end_minute integer not null check (end_minute between 1 and 1440),
  check (end_minute > start_minute)
);
create index weekly_hours_provider_idx on weekly_hours (provider_id, weekday);

-- Date-specific exceptions. If a date has any rows they replace the weekly hours for
-- that date. A row with null minutes means closed all day.
create table availability_exceptions (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  date date not null,
  start_minute integer check (start_minute between 0 and 1439),
  end_minute integer check (end_minute between 1 and 1440),
  note text not null default '',
  check ((start_minute is null and end_minute is null) or (start_minute is not null and end_minute is not null and end_minute > start_minute))
);
create index availability_exceptions_provider_idx on availability_exceptions (provider_id, date);

create table clients (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (email = lower(email)),
  phone text,
  -- Private provider notes. Never shown to the client.
  notes text not null default '' check (char_length(notes) <= 5000),
  created_at timestamptz not null default now(),
  unique (provider_id, email)
);

create table appointments (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  kind text not null default 'booking' check (kind in ('booking', 'block')),
  status text not null check (status in ('pending', 'confirmed', 'cancelled', 'declined', 'expired')),
  service_id uuid references services(id) on delete set null,
  client_id uuid references clients(id) on delete set null,
  service_name text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  -- ends_at plus the provider's buffer at booking time. The overlap guard uses this.
  occupied_until timestamptz not null,
  provider_timezone text not null,
  client_timezone text,
  client_note text check (char_length(client_note) <= 1000),
  title text,
  source text not null default 'client' check (source in ('client', 'provider')),
  expires_at timestamptz,
  -- Bumped to revoke previously issued manage links (links are HMAC-signed, never stored).
  token_version integer not null default 1,
  cancelled_by text check (cancelled_by in ('client', 'provider', 'system')),
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at),
  check (occupied_until >= ends_at),
  check (kind = 'block' or client_id is not null or status not in ('pending', 'confirmed')),
  check (status <> 'pending' or expires_at is not null),
  -- Atomic double-booking guard: no two live rows for a provider may overlap,
  -- whether they come from clients, manual entries or blocked time.
  constraint appointments_no_overlap exclude using gist (
    provider_id with =,
    tstzrange(starts_at, occupied_until, '[)') with &&
  ) where (status in ('pending', 'confirmed'))
);
create index appointments_provider_time_idx on appointments (provider_id, starts_at);
create index appointments_client_idx on appointments (client_id);

-- Private-mode access. A request is approved into a revocable, expiring link.
create table access_grants (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (email = lower(email)),
  message text not null default '' check (char_length(message) <= 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined', 'revoked')),
  expires_at timestamptz,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
create index access_grants_provider_idx on access_grants (provider_id, status);

-- Outbox for emails. The worker claims rows with FOR UPDATE SKIP LOCKED; dedupe_key
-- makes enqueueing idempotent, and reminders carry the start time they were made for.
create table notifications (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references providers(id) on delete cascade,
  appointment_id uuid references appointments(id) on delete cascade,
  access_grant_id uuid references access_grants(id) on delete cascade,
  kind text not null,
  to_email text not null,
  subject text not null,
  body text not null,
  send_after timestamptz not null default now(),
  for_starts_at timestamptz,
  status text not null default 'queued' check (status in ('queued', 'sending', 'sent', 'previewed', 'cancelled', 'failed', 'skipped')),
  attempts integer not null default 0,
  locked_until timestamptz,
  last_error text,
  sent_at timestamptz,
  dedupe_key text not null unique,
  created_at timestamptz not null default now()
);
create index notifications_due_idx on notifications (status, send_after);

-- Fixed-window counters for basic abuse protection.
create table rate_limits (
  key text not null,
  window_start timestamptz not null,
  count integer not null default 0,
  primary key (key, window_start)
);

-- ===== 20260930000002_rls.sql =====
-- Row level security for Supabase. The Next.js server talks to Postgres through
-- DATABASE_URL (a privileged role) and enforces ownership in code; these policies are
-- defense in depth for anything that reaches the tables through the Supabase API with
-- the anon or authenticated keys.
--
-- Anonymous users get no direct table access at all: public profiles and slots are
-- served by the app server, which never returns private data.

alter table providers enable row level security;
alter table services enable row level security;
alter table weekly_hours enable row level security;
alter table availability_exceptions enable row level security;
alter table clients enable row level security;
alter table appointments enable row level security;
alter table access_grants enable row level security;
alter table notifications enable row level security;
alter table rate_limits enable row level security;

create policy providers_owner on providers
  for all to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy services_owner on services
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy weekly_hours_owner on weekly_hours
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy availability_exceptions_owner on availability_exceptions
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy clients_owner on clients
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy appointments_owner on appointments
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy access_grants_owner on access_grants
  for all to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

create policy notifications_owner_read on notifications
  for select to authenticated
  using (exists (select 1 from providers p where p.id = provider_id and p.owner_id = auth.uid()));

-- rate_limits: no policies, so only the server role can use it.

-- ===== 20260930000003_lockdown_rls.sql =====
-- Supabase only. The migration log lives in the public schema too; with RLS on and no
-- policies, the Supabase Data API (anon and authenticated keys) can't read or change it.
-- Only the server's database role can.
alter table if exists schema_migrations enable row level security;

-- Simulated demo sign-in tables, in case this database was used in demo mode first.
alter table if exists demo_users enable row level security;
alter table if exists demo_sessions enable row level security;

-- ===== 20260930000004_search.sql =====
-- Name search on the home page.
-- profession: a short public line under the name ("Barber", "Maths tutor").
-- listed: whether the provider shows up when clients search by name. An exact @username
-- always finds them; invite-only (private) providers never appear in name search.
alter table providers add column if not exists profession text not null default '' check (char_length(profession) <= 60);
alter table providers add column if not exists listed boolean not null default true;
create index if not exists providers_display_name_lower_idx on providers (lower(display_name));

insert into schema_migrations (name) values
  ('20260930000001_schema.sql'),
  ('20260930000002_rls.sql'),
  ('20260930000003_lockdown_rls.sql'),
  ('20260930000004_search.sql')
on conflict do nothing;

commit;
