// Builds supabase/schema.sql: every migration in one script you can paste into the
// Supabase SQL editor. It also records the migrations as applied, so the app's own
// migration runner treats the database as up to date.
import fs from "node:fs";
import path from "node:path";

export function schemaBundle(root = process.cwd()) {
  const dir = path.join(root, "supabase", "migrations");
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
  const parts = [
    "-- Ayslock database schema for Supabase. Generated by `npm run db:schema`; do not edit by hand.",
    "-- Paste into Supabase → SQL Editor → New query → Run. Safe to run once on an empty project.",
    "-- (You can also skip this: the app applies the same migrations itself on first start.)",
    "",
    "begin;",
    "",
  ];
  parts.push("create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());", "");
  for (const f of files) {
    parts.push(`-- ===== ${f} =====`, fs.readFileSync(path.join(dir, f), "utf8").trimEnd(), "");
  }
  parts.push(
    "insert into schema_migrations (name) values",
    files.map((f) => `  ('${f}')`).join(",\n") + "\non conflict do nothing;",
    "",
    "commit;",
    "",
  );
  return parts.join("\n");
}
